name: Quality Analysis
on:
  push:
    paths:
      - 'src/**'
      - 'pom.xml'
      - 'README.md'
      - '.github/workflows/pipeline.yaml'
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'src/**'
      - 'pom.xml'
      - '.github/workflows/pipeline.yaml'
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build:
    name: Quality Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
          cache: 'maven'

      - name: Build and Test
        id: maven-build
        run: mvn -B verify

      - name: Sonar Analysis
        if: always()
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: > 
          mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar 
          -Dsonar.projectKey=${{ github.repository_owner }}_${{ github.event.repository.name }} 
          -Dsonar.qualitygate.wait=false
          -Dsonar.java.test.binaries=target/test-classes